---
- name: Instalar herramientas de Kubernetes en todos los nodos
  hosts: k8s_nodes
  gather_facts: true
  tasks:
    - name: Instalar python3-debian (dependencia de deb822_repository)
      ansible.builtin.apt:
        name: python3-debian
        state: present
        lock_timeout: 300

    - name: Descargar la clave GPG del repositorio de Kubernetes
      ansible.builtin.get_url:
        url: "https://pkgs.k8s.io/core:/stable:/{{ k8s_major_version }}/deb/Release.key"
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
        mode: "0644"

    - name: Añadir el repositorio oficial de Kubernetes
      ansible.builtin.deb822_repository:
        name: kubernetes
        types: deb
        uris: "https://pkgs.k8s.io/core:/stable:/{{ k8s_major_version }}/deb/"
        suites: "/"
        signed_by: /etc/apt/keyrings/kubernetes-apt-keyring.asc

    - name: Instalar kubelet, kubeadm y kubectl
      ansible.builtin.apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: true
        lock_timeout: 300

    - name: Evitar que se actualicen automáticamente kubelet, kubeadm y kubectl
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Arrancar y habilitar el servicio kubelet
      ansible.builtin.systemd:
        name: kubelet
        state: started
        enabled: true
