apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-database-secret
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: my-database-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: my.secrets/my-database
        property: username
    - secretKey: password
      remoteRef:
        key: my.secrets/my-database
        property: password
