apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-demo
  labels:
    app: liveness-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liveness-demo
  template:
    metadata:
      labels:
        app: liveness-demo
    spec:
      containers:
        - name: demo
          image: nginx:latest
          ports:
            - containerPort: 80
          lifecycle:
            postStart:
              exec:
                command:
                  # Creamos un archivo que el probe usará
                  - /bin/sh
                  - -c
                  - echo "OK" > /usr/share/nginx/html/healthz
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
