apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness-demo
  labels:
    app: readiness-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readiness-demo
  template:
    metadata:
      labels:
        app: readiness-demo
    spec:
      containers:
        - name: demo
          image: nginx:stable
          ports:
            - containerPort: 80
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    # Simula que la app tarda 15s en estar lista
                    (sleep 15; echo "READY" > /usr/share/nginx/html/readyz) &
          readinessProbe:
            httpGet:
              path: /readyz
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 3
            timeoutSeconds: 2
            failureThreshold: 3
