apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ .Chart.Name }}
  labels:
    type: local
spec:
  #storageClassName: standard
  accessModes:
    - {{ .Values.accessmode }}
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: {{ .Values.maxstorage }}
  hostPath:
    path: {{ .Values.mountdir }}
  claimRef:
    namespace: default
    name: pvc-{{ .Chart.Name }}
