apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Chart.Name }}
  annotations:
    service-app: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: 3000
      nodePort: {{ .Values.nodePort }}
  type: NodePort
