[rke2_servers]
rke2-server1 ansible_host=10.207.154.61 lxd_cpu=2 lxd_mem=4GiB lxd_disk=20GiB
rke2-server2 ansible_host=10.207.154.62 lxd_cpu=2 lxd_mem=4GiB lxd_disk=20GiB
rke2-server3 ansible_host=10.207.154.63 lxd_cpu=2 lxd_mem=4GiB lxd_disk=20GiB

[rke2_workers]
rke2-worker1 ansible_host=10.207.154.64 lxd_cpu=2 lxd_mem=2GiB lxd_disk=20GiB
rke2-worker2 ansible_host=10.207.154.65 lxd_cpu=2 lxd_mem=2GiB lxd_disk=20GiB
rke2-worker3 ansible_host=10.207.154.66 lxd_cpu=2 lxd_mem=2GiB lxd_disk=20GiB

[rke2_cluster:children]
rke2_servers
rke2_workers

[all:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
