---
- name: Destruir el nodo Kubernetes LXD
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Detener y eliminar la máquina virtual del nodo k8s
      community.general.lxd_container:
        name: "{{ item }}"
        type: virtual-machine
        state: absent
        timeout: 30
      loop: "{{ groups['k8s_nodes'] }}"

    - name: Confirmación de eliminación
      ansible.builtin.debug:
        msg: "El nodo Kubernetes LXD {{ item }} ha sido eliminado con éxito."
      loop: "{{ groups['k8s_nodes'] }}"
