# Inventario para nodo único de Kubernetes en LXD
# Asigna IP estática y recursos básicos

[k8s_nodes]
k8s-single ansible_host=10.207.154.50 lxd_cpu=2 lxd_mem=4GB lxd_disk=40GB

[cluster:children]
k8s_nodes
