services:
  nodeapp:
    ports:
      - 3001:3000
    container_name: nodeapp
    env_file:
      - .env
    networks:
      - nodenet
    volumes:
      - ./uploads:/app/uploads
    image: ${DOCKER_HUB_USER}/${DOCKER_HUB_REPOSITORY}:${DOCKER_HUB_TAG}
networks:
  nodenet:
    name: nodenet
    driver: bridge