apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    service-app: nginx
spec:
  selector:
    app: v1
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
