---
- name: Prepare the Ceph cluster nodes
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    lxd_machine_provision_group: ceph_nodes
  roles:
    - lxd_machine_provision

- name: Prepare the Kubernetes nodes
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    lxd_machine_provision_group: k8s_nodes
  roles:
    - lxd_machine_provision
