apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ejemplo
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: standard
  # volumeName: pv-ejemplo
  resources:
    requests:
      storage: 2Gi
