apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ejemplo
  labels:
    type: local
spec:
  #storageClassName: standard
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/data
  claimRef:
    namespace: default
    name: pvc-ejemplo-v2
