# Despliegue de servidor Nginx con PersistentVolumeClaim
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-v2

# Especificaciones del despliegue
spec:
  replicas: 1 # Numero de replicas del pod nginx
  selector:
    matchLabels:
      app: nginx
      environment: dev
  template:
    metadata:
      labels:
        app: nginx
        environment: dev
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          securityContext:
            privileged: true
          ports:
            - containerPort: 80
              name: "http-server"
              # Volumen que monta el pod
          volumeMounts:
            - name: pvc-storage
              mountPath: "/usr/share/nginx/html"
      volumes:
        - name: pvc-storage
          # Se reclama el PersistentVolumeClaim creado anteriormente
          persistentVolumeClaim:
            claimName: pvc-ejemplo-v2

