apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mi-secreto
  annotations: # para quitar un warning
    kubectl.kubernetes.io/last-applied-configuration: ""
data:
  key1: c3VwZXJzZWNyZXQK  # "supersecret" codificado en base64
  key2: dG9wc2VjcmV0Cg==  # "topsecret" codificado en base64

