# Inventario para clúster de Kubernetes en LXD (1 Manager + 2 Workers)
# Asigna IP estática y recursos básicos a cada nodo

[control_plane]
k8s-manager ansible_host=10.207.154.50 lxd_cpu=2 lxd_mem=3GB lxd_disk=20GB

[workers]
k8s-worker1 ansible_host=10.207.154.51 lxd_cpu=2 lxd_mem=2GB lxd_disk=15GB
k8s-worker2 ansible_host=10.207.154.52 lxd_cpu=2 lxd_mem=2GB lxd_disk=15GB

[k8s_nodes:children]
control_plane
workers
