apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-nginx
  labels:
    app: v1
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v1
      environment: dev
  template:
    metadata:
      labels:
        app: v1
        environment: dev
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
