apiVersion: v1
kind: LimitRange
metadata:
  name: lr-cuarta-parte
  namespace: limitado
spec:
  limits:
    - type: Container
      default:
        cpu: "250m"
        memory: "512Mi"
      defaultRequest:
        cpu: "200m"
        memory: "256Mi"
      max:
        cpu: "1"
        memory: "4Gi"
      min:
        cpu: "50m"
        memory: "64Mi"
